# Generated by Django 6.0 on 2026-02-04 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="categoria",
            name="icono",
        ),
        migrations.AddField(
            model_name="pedido",
            name="es_urgente",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="mesa",
            name="estado",
            field=models.CharField(
                choices=[
                    ("libre", "Libre"),
                    ("ocupada", "Ocupada"),
                    ("esperando", "Esperando Comida"),
                    ("lista", "Comida Lista"),
                    ("pagar", "Por Pagar"),
                ],
                default="libre",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="estado",
            field=models.CharField(
                choices=[("pendiente", "Pendiente"), ("listo", "Listo")],
                default="pendiente",
                max_length=20,
            ),
        ),
    ]
