# Generated by Django 6.0 on 2026-02-04 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_categoria_icono_pedido_es_urgente_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="descripcion",
            field=models.TextField(
                blank=True, help_text="Ej: Incluye papas y bebida", null=True
            ),
        ),
    ]
