# Generated by Django 6.0 on 2026-02-09 13:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_producto_imagen_alter_producto_descripcion"),
    ]

    operations = [
        migrations.CreateModel(
            name="Venta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_venta",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("total", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "pedido",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="core.pedido"
                    ),
                ),
            ],
        ),
    ]
