# Generated by Django 6.0 on 2026-02-09 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_venta"),
    ]

    operations = [
        migrations.AddField(
            model_name="venta",
            name="metodo_pago",
            field=models.CharField(default="efectivo", max_length=50),
        ),
    ]
