# Generated by Django 6.0 on 2026-02-10 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_pedido_usuario"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="cliente_cedula",
            field=models.CharField(
                blank=True, max_length=13, null=True, verbose_name="Cédula Cliente"
            ),
        ),
        migrations.AddField(
            model_name="pedido",
            name="metodo_pago",
            field=models.CharField(default="efectivo", max_length=20),
        ),
        migrations.AddField(
            model_name="pedido",
            name="total",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
